import Head from "next/head";
import { useRouter } from "next/router";
import DoForm from "../components/DoForm/DoForm";
import DoTabs from "../components/DoTabs/DoTabs";
import DoItem from "../components/DoList/DoItem";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const TABS_MAP = {
  All: () => true,
  Active: (item) => item.active,
  Done: (item) => !item.active,
  Kill: () => true,
};

const TABS_NAMES = Object.keys(TABS_MAP);

function Home(props) {
  const router = useRouter();
  // const [toDoList, setToDoList] = useState(data);
  const [filterState, setFilterState] = useState("All");

  // Functions
  async function addToDo(enteredItem) {
    const response = await fetch("/api/to-do-list", {
      method: "POST",
      body: JSON.stringify(enteredItem),
      headers: {
        "Content-Type": "application/json",
      },
    });

    console.log(enteredItem);

    const list = await response.json();

    console.log(list);

    router.push("/");
  }

  async function toggleActive(id) {
    const response = await fetch("/api/to-do-list", {
      method: "PATCH",
      body: JSON.stringify(id),
      headers: {
        "Content-Type": "application/json",
      },
    });

    const list = await response.json();

    console.log(list);

    router.push("/");
  }

  //   const toggleActive = (id) => {
  //   const updatedList = toDoList.map((item) => {
  //     if (id === item.id) {
  //       return { ...item, active: !item.active };
  //     }
  //     return item;
  //   });
  //   setToDoList(updatedList);
  // };

  // setToDoList((prevItems) => {
  //   const newList = [...prevItems];
  //   newList.unshift({
  //     value: enteredText,
  //     active: true,
  //     id: Math.random().toString(),
  //   });
  //   return newList;
  // });

  // const deleteItem = (itemId) => {
  //   setToDoList((prevItems) => {
  //     const newList = prevItems.filter((item) => item.id !== itemId);
  //     return newList;
  //   });
  // };

  // const deleteAllDone = () => {
  //   setToDoList((prevItems) => {
  //     const newList = prevItems.filter((item) => item.active === true);
  //     return newList;
  //   });
  // };

  // Component Lists
  const tabsList = TABS_NAMES.map((name) => (
    <DoTabs
      key={name}
      name={name}
      setFilterState={setFilterState}
      // deleteAllDone={deleteAllDone}
    />
  ));

  const itemsList = props.toDoList.filter(TABS_MAP[filterState]).map((item) => (
    <DoItem
      item={item.item}
      active={item.active}
      id={item._id}
      key={item._id}
      toggleActive={toggleActive}
      // deleteItem={deleteItem}
    ></DoItem>
  ));

  let content = <p className={styles.placeholder}>List is empty</p>;

  if (props.toDoList.length > 0) {
    content = <ul className={styles["to-do-items"]}>{itemsList}</ul>;
  }

  // return
  return (
    <div className={styles.container}>
      <Head>
        <title>Do Did</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.pad}>
          <DoForm addToDo={addToDo}></DoForm>

          <div className={styles["tabs-container"]}>{tabsList}</div>

          <div>{content}</div>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch(`${process.env.API_BASE_URL}/to-do-list`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  const toDoList = await response.json();

  return {
    props: {
      toDoList,
    },
  };
}

export default Home;
